version: '3.8'
services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "13306:3306"
    volumes:
      - ./mysql/sql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: wjh
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_HOST: "%"
    container_name: mysql  # 可选，可以去掉
    networks:
      - mysql_net
    restart: always  # 可选，可以改为 on-failure
  nacos:
    image: nacos/nacos-server:v2.1.1
    container_name: nacos
    restart: always
    privileged: true
    environment:
      - MODE= standalone
      - SPRING_DATASOURCE_PLATFORM= mysql
      - MYSQL_SERVICE_HOST= mysql  # 或宿主机的实际 IP（如 192.168.x.x）
      - MYSQL_SERVICE_PORT= 3306
      - MYSQL_SERVICE_USER= root
      - MYSQL_SERVICE_PASSWORD= 123456
      - MYSQL_SERVICE_DB_NAME= nacos
      - TIME_ZONE= Asia/Shanghai
    depends_on:
      - mysql
    networks:
      - mysql_net
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
networks:
  mysql_net:
    driver: bridge
volumes:
  mysql_data:  # 声明一个命名卷，Docker 会自动管理其存储位置